import { PatientWithDocuments } from '../types/medicalDocuments';

export interface MockPatient {
  id: string;
  patient_number: string;
  first_name: string;
  last_name: string;
  date_of_birth: string;
  gender: 'male' | 'female';
  blood_group: string;
  phone: string;
  email: string;
  address: string;
  city: string;
  allergies?: string[];
  medical_history?: string[];
}

const MOCK_PATIENTS: MockPatient[] = [
  {
    id: 'mock-patient-001',
    patient_number: 'PAT-601001',
    first_name: 'Jean',
    last_name: 'Dupont',
    date_of_birth: '1985-03-15',
    gender: 'male',
    blood_group: 'A+',
    phone: '+243 812 345 678',
    email: 'jean.dupont@email.cd',
    address: 'Avenue Kasa-Vubu 123',
    city: 'Kinshasa',
    allergies: ['Pénicilline'],
    medical_history: ['Hypertension'],
  },
  {
    id: 'mock-patient-002',
    patient_number: 'PAT-601002',
    first_name: 'Marie',
    last_name: 'Koffi',
    date_of_birth: '1990-07-22',
    gender: 'female',
    blood_group: 'O+',
    phone: '+243 823 456 789',
    email: 'marie.koffi@email.cd',
    address: 'Boulevard du 30 Juin 45',
    city: 'Kinshasa',
    allergies: [],
    medical_history: ['Diabète Type 2'],
  },
  {
    id: 'mock-patient-003',
    patient_number: 'PAT-601003',
    first_name: 'Paul',
    last_name: 'Mbala',
    date_of_birth: '1978-11-30',
    gender: 'male',
    blood_group: 'B+',
    phone: '+243 834 567 890',
    email: 'paul.mbala@email.cd',
    address: 'Rue Kabasele 67',
    city: 'Lubumbashi',
    allergies: ['Aspirine', 'Fruits de mer'],
    medical_history: [],
  },
  {
    id: 'mock-patient-004',
    patient_number: 'PAT-601004',
    first_name: 'Sophie',
    last_name: 'Lukeni',
    date_of_birth: '1995-05-18',
    gender: 'female',
    blood_group: 'AB+',
    phone: '+243 845 678 901',
    email: 'sophie.lukeni@email.cd',
    address: 'Avenue Lumumba 89',
    city: 'Kinshasa',
    allergies: ['Lactose'],
    medical_history: ['Asthme'],
  },
  {
    id: 'mock-patient-005',
    patient_number: 'PAT-601005',
    first_name: 'André',
    last_name: 'Kabila',
    date_of_birth: '1982-09-12',
    gender: 'male',
    blood_group: 'O-',
    phone: '+243 856 789 012',
    email: 'andre.kabila@email.cd',
    address: 'Boulevard Triomphal 34',
    city: 'Kinshasa',
    allergies: [],
    medical_history: ['Ulcère gastrique'],
  },
  {
    id: 'mock-patient-006',
    patient_number: 'PAT-601006',
    first_name: 'Claire',
    last_name: 'Tshisekedi',
    date_of_birth: '1988-02-25',
    gender: 'female',
    blood_group: 'A-',
    phone: '+243 867 890 123',
    email: 'claire.tshisekedi@email.cd',
    address: 'Rue de la Gombe 56',
    city: 'Kinshasa',
    allergies: ['Pollen'],
    medical_history: [],
  },
  {
    id: 'mock-patient-007',
    patient_number: 'PAT-601007',
    first_name: 'David',
    last_name: 'Lumingu',
    date_of_birth: '1975-12-08',
    gender: 'male',
    blood_group: 'B-',
    phone: '+243 878 901 234',
    email: 'david.lumingu@email.cd',
    address: 'Avenue Sendwe 78',
    city: 'Lubumbashi',
    allergies: [],
    medical_history: ['Hypertension', 'Cholestérol'],
  },
  {
    id: 'mock-patient-008',
    patient_number: 'PAT-601008',
    first_name: 'Emma',
    last_name: 'Mobutu',
    date_of_birth: '1993-06-14',
    gender: 'female',
    blood_group: 'AB-',
    phone: '+243 889 012 345',
    email: 'emma.mobutu@email.cd',
    address: 'Rue Yolo 12',
    city: 'Kinshasa',
    allergies: ['Arachides'],
    medical_history: [],
  },
  {
    id: 'mock-patient-009',
    patient_number: 'PAT-601009',
    first_name: 'François',
    last_name: 'Mulamba',
    date_of_birth: '1980-04-20',
    gender: 'male',
    blood_group: 'O+',
    phone: '+243 890 123 456',
    email: 'francois.mulamba@email.cd',
    address: 'Boulevard Lumumba 90',
    city: 'Kinshasa',
    allergies: [],
    medical_history: ['Arthrite'],
  },
  {
    id: 'mock-patient-010',
    patient_number: 'PAT-601010',
    first_name: 'Grace',
    last_name: 'Kabongo',
    date_of_birth: '1992-08-05',
    gender: 'female',
    blood_group: 'A+',
    phone: '+243 801 234 567',
    email: 'grace.kabongo@email.cd',
    address: 'Avenue Kasai 23',
    city: 'Kananga',
    allergies: ['Iode'],
    medical_history: [],
  },
  {
    id: 'mock-patient-011',
    patient_number: 'PAT-601011',
    first_name: 'Henri',
    last_name: 'Nkulu',
    date_of_birth: '1987-01-17',
    gender: 'male',
    blood_group: 'B+',
    phone: '+243 812 345 678',
    email: 'henri.nkulu@email.cd',
    address: 'Rue Mokolo 45',
    city: 'Kinshasa',
    allergies: [],
    medical_history: ['Migraines chroniques'],
  },
  {
    id: 'mock-patient-012',
    patient_number: 'PAT-601012',
    first_name: 'Isabelle',
    last_name: 'Mwamba',
    date_of_birth: '1991-10-28',
    gender: 'female',
    blood_group: 'O-',
    phone: '+243 823 456 789',
    email: 'isabelle.mwamba@email.cd',
    address: 'Avenue Nyembo 67',
    city: 'Lubumbashi',
    allergies: ['Latex'],
    medical_history: [],
  },
  {
    id: 'mock-patient-013',
    patient_number: 'PAT-601013',
    first_name: 'Jacques',
    last_name: 'Kalala',
    date_of_birth: '1979-03-11',
    gender: 'male',
    blood_group: 'AB+',
    phone: '+243 834 567 890',
    email: 'jacques.kalala@email.cd',
    address: 'Boulevard Kasa-Vubu 89',
    city: 'Kinshasa',
    allergies: [],
    medical_history: ['Diabète Type 1'],
  },
  {
    id: 'mock-patient-014',
    patient_number: 'PAT-601014',
    first_name: 'Kiara',
    last_name: 'Ndombele',
    date_of_birth: '1996-07-03',
    gender: 'female',
    blood_group: 'A-',
    phone: '+243 845 678 901',
    email: 'kiara.ndombele@email.cd',
    address: 'Rue Kintambo 34',
    city: 'Kinshasa',
    allergies: ['Gluten'],
    medical_history: [],
  },
  {
    id: 'mock-patient-015',
    patient_number: 'PAT-601015',
    first_name: 'Laurent',
    last_name: 'Tshombe',
    date_of_birth: '1983-12-19',
    gender: 'male',
    blood_group: 'B-',
    phone: '+243 856 789 012',
    email: 'laurent.tshombe@email.cd',
    address: 'Avenue Mobutu 56',
    city: 'Kisangani',
    allergies: [],
    medical_history: ['Hypertension'],
  },
  {
    id: 'mock-patient-016',
    patient_number: 'PAT-601016',
    first_name: 'Monique',
    last_name: 'Kasongo',
    date_of_birth: '1989-05-22',
    gender: 'female',
    blood_group: 'O+',
    phone: '+243 867 890 123',
    email: 'monique.kasongo@email.cd',
    address: 'Boulevard Lualaba 78',
    city: 'Kolwezi',
    allergies: ['Sulfamides'],
    medical_history: [],
  },
  {
    id: 'mock-patient-017',
    patient_number: 'PAT-601017',
    first_name: 'Nicolas',
    last_name: 'Banza',
    date_of_birth: '1977-09-30',
    gender: 'male',
    blood_group: 'A+',
    phone: '+243 878 901 234',
    email: 'nicolas.banza@email.cd',
    address: 'Rue Tshimanga 90',
    city: 'Mbuji-Mayi',
    allergies: [],
    medical_history: ['Cholestérol élevé'],
  },
  {
    id: 'mock-patient-018',
    patient_number: 'PAT-601018',
    first_name: 'Olivia',
    last_name: 'Yuma',
    date_of_birth: '1994-02-14',
    gender: 'female',
    blood_group: 'AB-',
    phone: '+243 889 012 345',
    email: 'olivia.yuma@email.cd',
    address: 'Avenue Kabinda 12',
    city: 'Kinshasa',
    allergies: ['Nickel'],
    medical_history: [],
  },
  {
    id: 'mock-patient-019',
    patient_number: 'PAT-601019',
    first_name: 'Patrick',
    last_name: 'Ilunga',
    date_of_birth: '1986-11-07',
    gender: 'male',
    blood_group: 'B+',
    phone: '+243 890 123 456',
    email: 'patrick.ilunga@email.cd',
    address: 'Rue Katanga 45',
    city: 'Lubumbashi',
    allergies: [],
    medical_history: ['Asthme'],
  },
  {
    id: 'mock-patient-020',
    patient_number: 'PAT-601020',
    first_name: 'Rachel',
    last_name: 'Mutombo',
    date_of_birth: '1998-04-26',
    gender: 'female',
    blood_group: 'O-',
    phone: '+243 801 234 567',
    email: 'rachel.mutombo@email.cd',
    address: 'Boulevard Sendwe 67',
    city: 'Kinshasa',
    allergies: ['Codéine'],
    medical_history: [],
  },
];

export function getAllMockPatients(): PatientWithDocuments[] {
  return MOCK_PATIENTS.map(patient => ({
    ...patient,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    emergency_contact: patient.phone,
    insurance_number: `INS-${patient.patient_number.split('-')[1]}`,
    document_count: 0,
    document_types: [],
    assigned_documents: [],
  }));
}

export function getRandomMockPatient(): PatientWithDocuments {
  const randomIndex = Math.floor(Math.random() * MOCK_PATIENTS.length);
  const patient = MOCK_PATIENTS[randomIndex];

  return {
    ...patient,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    emergency_contact: patient.phone,
    insurance_number: `INS-${patient.patient_number.split('-')[1]}`,
    document_count: 0,
    document_types: [],
    assigned_documents: [],
  };
}

export function getMockPatientById(id: string): PatientWithDocuments | undefined {
  const patient = MOCK_PATIENTS.find(p => p.id === id);

  if (!patient) return undefined;

  return {
    ...patient,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    emergency_contact: patient.phone,
    insurance_number: `INS-${patient.patient_number.split('-')[1]}`,
    document_count: 0,
    document_types: [],
    assigned_documents: [],
  };
}

export function getMockPatientByIndex(index: number): PatientWithDocuments {
  const patient = MOCK_PATIENTS[index % MOCK_PATIENTS.length];

  return {
    ...patient,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    emergency_contact: patient.phone,
    insurance_number: `INS-${patient.patient_number.split('-')[1]}`,
    document_count: 0,
    document_types: [],
    assigned_documents: [],
  };
}

export function getMockPatientCount(): number {
  return MOCK_PATIENTS.length;
}
